### ISSUE TITLE
Template No Work - perl -v 5.20.2 or 5.32.0

### ISSUE THREAD

**Issue by lorenzo8769** [itdependsnetworks/Config-Template#1]
Hi @itdependsnetworks 

I have been using your scripts for several years now and thanks to you I was able to generate tons of equipment configuration :-)

I realized that recently this no longer works. I don't know what it came from.

By resuming take 1, 2 or 3 directly on my web server, the template does not work:
When I fill in the fields and hit "Submit", instead of running the conf with the .tmpl file, the command saves me the final.pl file on my computer ...

Do you have an idea?

Thx Ken

Laurent

**Comment by itdependsnetworks** [comment]
I would guess something is wrong with your apache cgi process and it is not being interpreted as code. There are much more modern techniques and if you are in networking would suggest https://j2live.ttl255.com/, https://td4a.codethenetwork.com/, or joining a slack group at https://networktocode.herokuapp.com/
